field: 3a8fd138-ba51-4809-a6a9-0631219a8863 # Artist bio
fieldLayouts:
  d3efcaf0-cbe5-466f-810d-980e2e96ce5d:
    tabs:
      -
        elements:
          -
            fieldUid: b1a2c388-bc5b-4c69-a294-e1c73b7d3de0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 583cd6ce-8ce1-4756-a1c2-8b8dee79a822
            warning: null
            width: 100
        name: Content
        uid: 91b7d107-9bba-4c7e-b9d1-82f8ad663f5e
fields:
  b1a2c388-bc5b-4c69-a294-e1c73b7d3de0: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Supportive images for the artist''s bio. '
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:3e54d30c-8ad9-4386-9f8e-b5e7f34ba7f9' # Blog
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 3
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:f5a4fc28-3417-4fbb-a218-f43d6b1ef7b4' # Artist
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: artistBioImage
name: 'Artist bio image'
sortOrder: 2
