fieldLayouts:
  8fc0f3aa-4581-4676-b527-4d7599b1149c:
    tabs:
      -
        elements:
          -
            fieldUid: 124f479f-4c9f-4f89-934a-423e6702fe15 # About Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb19f08e-a1cb-4c28-9c4a-da2aa990aec4
            warning: null
            width: 100
          -
            fieldUid: 963c261f-a716-494f-965e-476b5a9e6705 # Post Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed44445a-1efe-4103-807e-20a0249e2b2c
            warning: null
            width: 100
        name: Content
        uid: 66cd75fd-ded1-4391-a560-c972b48b5833
handle: about
hasTitleField: false
name: About
section: 9dfd6e01-d3ee-4b8e-95b4-0de2f24ff887 # About
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
