fieldLayouts:
  344e8914-f81f-4680-a2d5-e1df1f02a4eb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74d068e9-1496-4f55-8cbc-73f2e705f3eb
            warning: null
            width: 100
        name: Content
        uid: 3a3ab56a-8381-4dbb-bace-9cfe0e7a570c
      -
        elements:
          -
            fieldUid: 5130a23c-2daf-4b1e-a9e8-af868f4e0e90 # Feature Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16dcd0f6-4256-40b7-a1ea-a7aa376d419f
            warning: null
            width: 100
          -
            fieldUid: 80dd8962-0161-4303-ba5e-bedbdc712424 # Post Categories
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd231d7b-f8bb-400a-8499-35d9c8429e22
            warning: null
            width: 100
          -
            fieldUid: 963c261f-a716-494f-965e-476b5a9e6705 # Post Content
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45ef5cd1-1a1e-4c83-a90e-a5dc504df819
            warning: null
            width: 100
          -
            fieldUid: d3f5ed75-a04a-4ac5-b281-1dcb82bdf1ed # Summary
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b17a9aa-d696-4c44-b254-1a21d4f3f10a
            warning: null
            width: 100
        name: 'Post Content'
        uid: b4d2218c-f808-4415-956d-fbf37c8428f8
handle: blog
hasTitleField: true
name: Blog
section: 13f85ac3-69bb-4927-b83d-6a808050c78a # Blog
sortOrder: 1
titleFormat: Headline
titleTranslationKeyFormat: null
titleTranslationMethod: site
