defaultPlacement: end
fieldLayouts:
  150ec93e-e330-46fd-82ac-74a548bb4c34:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5417e715-56cd-4886-a221-d6fc4d46b552
            warning: null
            width: 100
        name: Content
        uid: 48b118ef-1a3b-43f1-b12e-024c9ccd0e2c
handle: blogCategories
name: 'Blog Categories'
siteSettings:
  5868b6e2-0843-4f92-a1f3-16415121e6db: # Dan-macbook
    hasUrls: true
    template: blog/_category
    uriFormat: 'blog/categories/{slug}'
structure:
  maxLevels: 1
  uid: 1390f524-9a82-47ed-ba44-7bd7f650bbaf
