fieldLayouts:
  667661d9-3b00-4ea1-96b2-db910e8a49df:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: Event-name
            label: Event-name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ac4b34c2-6db9-4136-bec9-d9c4ea94af0f
            warning: null
            width: 100
        name: Content
        uid: 475c9b88-1b55-47ba-9e52-c98e03768373
fs: event
handle: event
name: Event
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
