fieldLayouts:
  dfe4c559-831c-4a4b-942f-0d4fadab94ff:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: faf20bac-7bc5-4b52-b8c5-664b4ff4b755
            warning: null
            width: 100
        name: Content
        uid: abe87295-435b-4bab-9ddb-5a02b9f2fa6f
fs: general
handle: general
name: General
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: '@webroot/assets/general'
