columnSuffix: xdobzguo
contentColumnType:
  - 'date:datetime'
  - 'tz:string'
fieldGroup: 18543997-cb5d-4a34-bc3d-f6c2aece0185 # Event fields
handle: eventDate
instructions: 'Date of your event'
name: event-date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 15
  showDate: true
  showTime: true
  showTimeZone: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
