columnSuffix: null
contentColumnType: string
fieldGroup: 18543997-cb5d-4a34-bc3d-f6c2aece0185 # Event fields
handle: eventCategories
instructions: 'Choose categories for your event'
name: event-categories
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:8c2bcebe-cb52-4e17-9188-b8800184f24a' # Event Categories
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
