columnSuffix: null
contentColumnType: string
fieldGroup: ba7f9ec4-676a-417b-a110-e00cde4b5b69 # Blog Post Fields
handle: postContent
instructions: null
name: 'Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
