columnSuffix: fyfjewig
contentColumnType: text
fieldGroup: ba7f9ec4-676a-417b-a110-e00cde4b5b69 # Blog Post Fields
handle: summary
instructions: 'Enter a brief, one or two sentence post summary.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
