fieldLayouts:
  bb8613fc-fb22-4421-8e8e-94dfddbdb889:
    tabs:
      -
        elements:
          -
            fieldUid: b8832bf5-cf9b-4224-bf44-bdc3723bd3b5 # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fffda76-20e5-4f53-b99b-3a8aa59ebe58
            warning: null
            width: 100
        name: Content
        uid: b98b5ef8-0b9c-4cd3-909b-92516c537645
handle: siteInformation
name: 'Site Information'
sortOrder: 1
