defaultPlacement: end
enableVersioning: true
handle: about
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - default
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  15e24cdd-ce29-4b9f-a362-3390280c25c5: # blog-nl
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: over-ons
  5868b6e2-0843-4f92-a1f3-16415121e6db: # blog-en
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
