defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  5868b6e2-0843-4f92-a1f3-16415121e6db: # Dan-macbook
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
